### ISSUE TITLE
Add 6th and 7th of January

### ISSUE THREAD

**Issue by bogdannbv** [backdevs/romanian-bank-holidays-api#40]
Link to law: https://legislatie.just.ro/Public/DetaliiDocumentAfis/265498

**ToDo:**
- [x] Add 6th of January as "Bobotează"
- [x] Add 7th of January as "Soborul Sfântului Ioan Botezătorul"
- [x] Remove `holidays` slice size
